[package]
name = "recordTracker"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.6"
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.6", features = ["sqlite", "runtime-tokio-native-tls"] }
chrono = "0.4"
tower-http = { version = "0.4", features = ["fs", "cors"] }
tokio = { version = "1", features = ["full"] }
